spring:
  application:
    name: springcrud
  datasource:
    username: root
    password: rootpassword
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/springcrud
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  resources:
    static-locations
      - classpath:/static/,
      - classpath:/static/vendor/
      - classpath:/static/custom/

  error:
    whitelabel:
      enabled: false
